// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsbupvsgmcyxytmkotcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzYnVwdnNnbWN5eHl0bWtvdGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzgzNjksImV4cCI6MjA2NTA1NDM2OX0.alZuo2sdAthjqUD7vEzgPiO5OJRFLR6wWCW3lV8RyZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);